### ISSUE TITLE
Filters using months doesn't properly show the results for most of them (http://cfrp-laval.github.io/analytics/)

### ISSUE THREAD

**Issue by blirette** [cfrp-laval/analytics#26] opened 2017-09-22 19:17 UTC
http://cfrp-laval.github.io/analytics/

When you try to use the "months" filter in the "Selon quelle période?" section, only October, November and December seems to work.

Ex. move to the calendar form (or stay in the basic state of the tool), select "September" in the "Selon quelle période?" section. No data is shown.

**Comment by blirette** [comment] 2017-09-22 19:28
Probably related to issue #8

**Comment by jamiefolsom** [comment] 2017-09-28 16:00
@blirette yes, I think this is a duplicate of #8. The API should handle single-digit values gracefully, but this can be fixed in the client (by zero-padding the integers for single-digit months in the request), so that's a quicker solution in this case.

**Comment by blirette** [comment] 2017-09-28 17:30
Perfect. I'll let @hspier take the lead on this then. Thanks!

**Comment by hspier** [comment] 2017-10-18 02:04
Also fixes #8

**Closed by hspier** 2017-10-18 02:04 UTC
Labels: bug, fixed
